version: '3'
services:
  db-1:
    build: 
      context: .
      dockerfile: Dockerfile_sql
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app-1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:5000"
    depends_on:
      - db-1